name: 'Compile JOSS Paper'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile paper
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: List files in the directory
        run: |
          echo "Root directory:"
          ls -la
          echo "Paper directory:"
          ls -la paper/
          find . -name "*.pdf" -type f

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: |
            paper/*.pdf
            **/*.pdf
        if: always()